version: '3'
services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:1.19.3
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl-options.conf:/etc/nginx/ssl-options.conf:ro
      - ./nginx/dhparam:/etc/nginx/dhparam:ro
      - /etc/letsencrypt:/etc/letsencrypt

  app:
    container_name: app
    image: 29th/personnel-app:latest
    restart: always
    environment:
      BASE_URL: https://personnel.29th.org
      API_HOST: https://api.29th.org
      COAT_DIR: https://api.29th.org/coats
      FORUM_VANILLA_BASE_URL: https://vanilla.29th.org
      FORUM_SMF_BASE_URL: https://29th.org/forums
      FORUM_DISCOURSE_BASE_URL: https://forums.29th.org
      WIKI_URL: https://29th.org/wiki
      PERSONNEL_V3_URL: https://www.29th.org

  api:
    container_name: api
    image: 29th/personnel-api:latest
    restart: always
    volumes:
      - /mnt/user_images/coats:/var/www/html/coats
    environment:
      DB_DEFAULT_DATABASE: $PERSONNEL_DB_DATABASE
      DB_DEFAULT_HOSTNAME: $PERSONNEL_DB_HOSTNAME
      DB_DEFAULT_USERNAME: $PERSONNEL_DB_USERNAME_READONLY
      DB_DEFAULT_PASSWORD: $PERSONNEL_DB_PASSWORD_READONLY
      DB_DEFAULT_PORT: $PERSONNEL_DB_PORT
      DB_FORUMS_DATABASE: $FORUMS_DB_DATABASE
      DB_FORUMS_HOSTNAME: $FORUMS_DB_HOSTNAME
      DB_FORUMS_USERNAME: $FORUMS_DB_USERNAME_READONLY
      DB_FORUMS_PASSWORD: $FORUMS_DB_PASSWORD_READONLY
      DB_FORUMS_PORT: $FORUMS_DB_PORT
      ENCRYPTION_KEY: $PERSONNEL_ENCRYPTION_KEY
      ADMIN_API_KEY: $PERSONNEL_ADMIN_API_KEY
      BASE_URL: https://api.29th.org
      CORS_HOST: https://personnel.29th.org
      VANILLA_BASE_URL: https://vanilla.29th.org
      VANILLA_API_KEY: ~
      DISCOURSE_BASE_URL: https://forums.29th.org
      DISCOURSE_API_KEY: $DISCOURSE_API_KEY_READONLY
      DISCOURSE_COOKIE_NAME: discourse_jwt
      DISCOURSE_SECRET_KEY: $DISCOURSE_SECRET_KEY
      DISCOURSE_ENLISTMENT_CATEGORY_ID: 37
      ENVIRONMENT: production
      DIR_COAT_PUBLIC: /var/www/html/coats/

  forums:
    container_name: forums
    image: 29th/forums:latest
    restart: always
    volumes:
      - /mnt/user_images/uploads:/var/www/html/uploads
    environment:
      DB_HOSTNAME: $FORUMS_DB_HOSTNAME:$FORUMS_DB_PORT
      DB_DATABASE: $FORUMS_DB_DATABASE
      DB_USERNAME: $FORUMS_DB_USERNAME
      DB_PASSWORD: $FORUMS_DB_PASSWORD
      COOKIE_SALT: $FORUMS_COOKIE_SALT
      COOKIE_DOMAIN: 29th.org
      UPDATE_TOKEN: $FORUMS_UPDATE_TOKEN
      MAIL_FROM_NAME: 29th ID
      MAIL_FROM_ADDRESS: noreply@29th.org
      MAIL_SMTP_HOSTNAME: $FORUMS_MAIL_SMTP_HOSTNAME
      MAIL_SMTP_USERNAME: $FORUMS_MAIL_SMTP_USERNAME
      MAIL_SMTP_PASSWORD: $FORUMS_MAIL_SMTP_PASSWORD
      MAIL_SMTP_PORT: $FORUMS_MAIL_SMTP_PORT
      MAIL_SMTP_SECURITY: $FORUMS_MAIL_SMTP_SECURITY
      CAPTCHA_PRIVATE_KEY: $FORUMS_CAPTCHA_PRIVATE_KEY
      CAPTCHA_PUBLIC_KEY: $FORUMS_CAPTCHA_PUBLIC_KEY
      PERSONNEL_HOST_NAME: personnel.29th.org
      DEBUG: 0

  phpbb:
    container_name: phpbb
    image: 29th/phpbb-forums:latest
    restart: always
    environment:
      DB_HOST: $PHPBB_DB_HOST
      DB_USER: $PHPBB_DB_USER
      DB_PASS: $PHPBB_DB_PASS
      DB_NAME: $PHPBB_DB_NAME

  smf:
    container_name: smf
    image: 29th/smf-forums:latest
    restart: always
    environment:
      DB_HOST: $SMF_DB_HOST
      DB_USER: $SMF_DB_USER
      DB_PASS: $SMF_DB_PASS
      DB_NAME: $SMF_DB_NAME
      SITE_URL: https://smf.29th.org
